  -- Cleaning DimProduct Table --
SELECT [ProductID]
      ,t1.[Name] as [Product Name]
      --,[ProductNumber]
      --,[MakeFlag]
      --,[FinishedGoodsFlag]
      --,[Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      ,[StandardCost]
      --,[ListPrice]
      --,[Size]
      --,[SizeUnitMeasureCode]
      --,[WeightUnitMeasureCode]
      --,[Weight]
      --,[DaysToManufacture]
      --,[ProductLine]
      --,[Class]
      --,[Style]
      ,t1.[ProductSubcategoryID]
	  ,t2.[Name] as [Product Subcategory] 
	  ,t3.[ProductCategoryID]
	  ,t3.[Name] as [Product Category]
      --,[ProductModelID]
      --,[SellStartDate]
      --,[SellEndDate]
      --,[DiscontinuedDate]
      --,[rowguid]
      --,[ModifiedDate]
FROM [AdventureWorks2022].[Production].[Product] t1
LEFT JOIN [Production].[ProductSubcategory]  t2 on t1.ProductSubcategoryID = t2.ProductSubcategoryID
LEFT JOIN [Production].[ProductCategory] t3 on t2.ProductCategoryID = t3.ProductCategoryID

-- Cleaning Dim SalesTerritory Table --
SELECT [TerritoryID]
      ,[Name] Region
      ,[CountryRegionCode] as Country
      ,[Group] as Continent
      --,[SalesYTD]
      --,[SalesLastYear]
      --,[CostYTD]
      --,[CostLastYear]
      --,[rowguid]	
      --,[ModifiedDate]
  FROM [AdventureWorks2022].[Sales].[SalesTerritory]

 -- Fact SalesOrderHeader--
SELECT [SalesOrderID]
      --,[RevisionNumber]
      ,[OrderDate]
      --,[DueDate]
      --,[ShipDate]
      --,[Status]
      --,[OnlineOrderFlag]
      --,[SalesOrderNumber]
      --,[PurchaseOrderNumber]
      --,[AccountNumber]
      ,[CustomerID]
      --,[SalesPersonID]
      ,[TerritoryID]
      --,[BillToAddressID]
      --,[ShipToAddressID]
      --,[ShipMethodID]
      --,[CreditCardID]
      --,[CreditCardApprovalCode]
      --,[CurrencyRateID]
      --,[SubTotal]
      --,[TaxAmt]
      --,[Freight]
      ,[TotalDue]
      --,[Comment]
      --,[rowguid]
      --,[ModifiedDate]
  FROM [AdventureWorks2022].[Sales].[SalesOrderHeader]

-- Fact SalesOrderDetail
SELECT [SalesOrderID]
      ,[SalesOrderDetailID]
      --,[CarrierTrackingNumber]
      ,[OrderQty]
      ,t0.[ProductID]
      --,[SpecialOfferID]
      --,[UnitPrice]
      --,[UnitPriceDiscount]
      ,[LineTotal]
	  ,[LineTotal] - OrderQty*StandardCost as [ProfitMargin]
      --,[rowguid]
      --,[ModifiedDate]
  FROM [AdventureWorks2022].[Sales].[SalesOrderDetail] t0
  LEFT JOIN [Production].[Product] t1 on t0.ProductID = t1.ProductID