title: "My Data Analyst Portfolio"
theme: jekyll-theme-minimal
sidebar:
  profile_picture: "Profile picture.jpg" # Place the image in your repository's `/assets/images/` folder.
  name: "Nguyen Hoai An Vo"
  email: "iya979597@gmail.com"
  linkedin: "https://www.linkedin.com/in/vnhoaian/"
  github: "https://github.com/anvo-2001"
