profile:
  picture: "assets/profile.jpg"  # Path to your profile picture
  name: "Your Name"
  title: "Data Analyst"
  email: "your.email@example.com"
  phone: "+1234567890"
  linkedin: "https://www.linkedin.com/in/yourprofile"
  github: "https://github.com/yourusername"
