profile:
  picture: "assets/images/profile.jpg"  # Path to your profile picture
  name: "Nguyen Hoai An Vo"
  title: "Data Analyst"
  email: "iya979597@gmail.com"
  linkedin: "https://www.linkedin.com/in/vnhoaian/"
#  github: "https://github.com/yourusername"
