title: Nguyen Hoai An Vo
logo: /assets/img/profile.jpg
description: Data Analyst Junior | MSc Data Science for Economics
<br><br>
Email:  "iya979597@gmail.com"
<br>
<a href="https://www.linkedin.com/in/vnhoaian/">View My LinkedIn Profile </a>

# show_downloads: true
theme: jekyll-theme-minimal
