title: Nguyen Hoai An Vo
logo: /assets/img/profile.jpg
description: Data Analyst Junior | MSc Data Science for Economics

email: "iya979597@gmail.com"
linkedin: "https://www.linkedin.com/in/vnhoaian/"

# show_downloads: true
theme: jekyll-theme-minimal
