title: An Vo
logo: /assets/img/profile.jpg
description: MSc Data Science for Economics at University of Liverpool, UK

email: "vnhoaian791@gmail.com"
linkedin: "https://www.linkedin.com/in/vnhoaian/"

# show_downloads: true
theme: jekyll-theme-minimal
